@startuml money_transfer_app_context
title Money Transfer Application
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

Person(user, "User")
System(system, "Money Transfer App")

Rel(user, system, "uses web app")

Person_Ext(admin, "Admin")
Rel(admin, system, "uses API")

@enduml
