spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://<host>:5432/<dbname>?ssl=true&sslmode=require
    username: <username>
    password: <password>
    initialization-mode: always
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include: '*'
