spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://top2.nearest.of.money-transfer-api-db.internal:5432/money_transfer_api?sslmode=disable
    username: money_transfer_api
    password: HeFy3vTYtH4sIJv
    initialization-mode: always
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include: '*'
