name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  # This workflow performs the following steps:
      - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
      - name: Set up JDK 11
        uses: actions/setup-java@v2 # The setup-java step configures the Java 11 JDK by Adoptium.
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven  # When using GitHub-hosted runners, you can cache your dependencies to speed up your workflow runs
      - name: Build with Maven  # The "Build with Maven" step runs the Maven package target in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
        run: mvn --batch-mode --update-snapshots verify
  deploy:
    needs: build  #If you have a job that must only run after another job has completed, you can use the needs keyword to create this dependency.
    runs-on: ubuntu-latest
    name: Deploy to Fly.io
    steps:
      # check out repository and flyctl deploy
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --app money-transfer-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

#    steps:
#      - uses: actions/checkout@v2
#      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          # Now go to your Heroku account and go to Account Settings. Scroll to the bottom until you see API Key. Copy this key and go to your project's repository on GitHub.
#          # In your Repo, go to Settings -> Secrets and click on "New Secret". Then enter HEROKU_API_KEY as the name and paste the copied API Key as the value.
#          # You can now push your project to GitHub and it will be automatically deployed to Heroku henceforth.
#          heroku_app_name: "money-transfer-api-biniam" #Must be unique in Heroku
#          heroku_email: "biniamasnake@gmail.com"
#          healthcheck: "https://money-transfer-api-biniam.herokuapp.com/actuator/health"
#          # Adding the url to the `healthcheck` option of the action will make the action attempt
#          # to perform a GET Request to that url and print the response if successful.
#          # Else it will fail the action to indicate that the deployment was not successful.
